namespace RiftCommon;

public enum EnemyType {
    None,
    SlimeGreen,
    SlimeBlue,
    SlimeYellow,
    BatBlue,
    BatYellow,
    BatRed,
    ZombieGreen,
    ZombieBlue,
    ZombieRed,
    SkeletonWhite,
    SkeletonWhiteShield,
    SkeletonWhiteDoubleShield,
    SkeletonYellow,
    SkeletonYellowShield,
    SkeletonBlack,
    SkeletonBlackShield,
    ArmadilloBlue,
    ArmadilloRed,
    ArmadilloYellow,
    Wyrm,
    HarpyGreen,
    HarpyBlue,
    HarpyRed,
    Blademaster,
    BlademasterBlue,
    BlademasterYellow,
    SkullWhite,
    SkullBlue,
    SkullRed,
    Apple,
    Cheese,
    Drumstick,
    Ham
}